ALTER TABLE ONLY public."IdentityProperties" DROP CONSTRAINT "FK_IdentityProperties_IdentityResources_IdentityResourceId";
ALTER TABLE ONLY public."IdentityClaims" DROP CONSTRAINT "FK_IdentityClaims_IdentityResources_IdentityResourceId";
ALTER TABLE ONLY public."ClientSecrets" DROP CONSTRAINT "FK_ClientSecrets_Clients_ClientId";
ALTER TABLE ONLY public."ClientScopes" DROP CONSTRAINT "FK_ClientScopes_Clients_ClientId";
ALTER TABLE ONLY public."ClientRedirectUris" DROP CONSTRAINT "FK_ClientRedirectUris_Clients_ClientId";
ALTER TABLE ONLY public."ClientProperties" DROP CONSTRAINT "FK_ClientProperties_Clients_ClientId";
ALTER TABLE ONLY public."ClientPostLogoutRedirectUris" DROP CONSTRAINT "FK_ClientPostLogoutRedirectUris_Clients_ClientId";
ALTER TABLE ONLY public."ClientIdPRestrictions" DROP CONSTRAINT "FK_ClientIdPRestrictions_Clients_ClientId";
ALTER TABLE ONLY public."ClientGrantTypes" DROP CONSTRAINT "FK_ClientGrantTypes_Clients_ClientId";
ALTER TABLE ONLY public."ClientCorsOrigins" DROP CONSTRAINT "FK_ClientCorsOrigins_Clients_ClientId";
ALTER TABLE ONLY public."ClientClaims" DROP CONSTRAINT "FK_ClientClaims_Clients_ClientId";
ALTER TABLE ONLY public."AspNetUserTokens" DROP CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId";
ALTER TABLE ONLY public."AspNetUserRoles" DROP CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId";
ALTER TABLE ONLY public."AspNetUserRoles" DROP CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId";
ALTER TABLE ONLY public."AspNetUserLogins" DROP CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId";
ALTER TABLE ONLY public."AspNetUserClaims" DROP CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId";
ALTER TABLE ONLY public."AspNetRoleClaims" DROP CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId";
ALTER TABLE ONLY public."ApiSecrets" DROP CONSTRAINT "FK_ApiSecrets_ApiResources_ApiResourceId";
ALTER TABLE ONLY public."ApiScopes" DROP CONSTRAINT "FK_ApiScopes_ApiResources_ApiResourceId";
ALTER TABLE ONLY public."ApiScopeClaims" DROP CONSTRAINT "FK_ApiScopeClaims_ApiScopes_ApiScopeId";
ALTER TABLE ONLY public."ApiProperties" DROP CONSTRAINT "FK_ApiProperties_ApiResources_ApiResourceId";
ALTER TABLE ONLY public."ApiClaims" DROP CONSTRAINT "FK_ApiClaims_ApiResources_ApiResourceId";
DROP INDEX public."UserNameIndex";
DROP INDEX public."RoleNameIndex";
DROP INDEX public."IX_PersistedGrants_SubjectId_ClientId_Type";
DROP INDEX public."IX_PersistedGrants_Expiration";
DROP INDEX public."IX_IdentityResources_Name";
DROP INDEX public."IX_IdentityProperties_IdentityResourceId";
DROP INDEX public."IX_IdentityClaims_IdentityResourceId";
DROP INDEX public."IX_DeviceCodes_Expiration";
DROP INDEX public."IX_DeviceCodes_DeviceCode";
DROP INDEX public."IX_Clients_ClientId";
DROP INDEX public."IX_ClientSecrets_ClientId";
DROP INDEX public."IX_ClientScopes_ClientId";
DROP INDEX public."IX_ClientRedirectUris_ClientId";
DROP INDEX public."IX_ClientProperties_ClientId";
DROP INDEX public."IX_ClientPostLogoutRedirectUris_ClientId";
DROP INDEX public."IX_ClientIdPRestrictions_ClientId";
DROP INDEX public."IX_ClientGrantTypes_ClientId";
DROP INDEX public."IX_ClientCorsOrigins_ClientId";
DROP INDEX public."IX_ClientClaims_ClientId";
DROP INDEX public."IX_AspNetUserRoles_RoleId";
DROP INDEX public."IX_AspNetUserLogins_UserId";
DROP INDEX public."IX_AspNetUserClaims_UserId";
DROP INDEX public."IX_AspNetRoleClaims_RoleId";
DROP INDEX public."IX_ApiSecrets_ApiResourceId";
DROP INDEX public."IX_ApiScopes_Name";
DROP INDEX public."IX_ApiScopes_ApiResourceId";
DROP INDEX public."IX_ApiScopeClaims_ApiScopeId";
DROP INDEX public."IX_ApiResources_Name";
DROP INDEX public."IX_ApiProperties_ApiResourceId";
DROP INDEX public."IX_ApiClaims_ApiResourceId";
DROP INDEX public."EmailIndex";
ALTER TABLE ONLY public."PersistedGrants" DROP CONSTRAINT "PK_PersistedGrants";
ALTER TABLE ONLY public."IdentityResources" DROP CONSTRAINT "PK_IdentityResources";
ALTER TABLE ONLY public."IdentityProperties" DROP CONSTRAINT "PK_IdentityProperties";
ALTER TABLE ONLY public."IdentityClaims" DROP CONSTRAINT "PK_IdentityClaims";
ALTER TABLE ONLY public."DeviceCodes" DROP CONSTRAINT "PK_DeviceCodes";
ALTER TABLE ONLY public."Clients" DROP CONSTRAINT "PK_Clients";
ALTER TABLE ONLY public."ClientSecrets" DROP CONSTRAINT "PK_ClientSecrets";
ALTER TABLE ONLY public."ClientScopes" DROP CONSTRAINT "PK_ClientScopes";
ALTER TABLE ONLY public."ClientRedirectUris" DROP CONSTRAINT "PK_ClientRedirectUris";
ALTER TABLE ONLY public."ClientProperties" DROP CONSTRAINT "PK_ClientProperties";
ALTER TABLE ONLY public."ClientPostLogoutRedirectUris" DROP CONSTRAINT "PK_ClientPostLogoutRedirectUris";
ALTER TABLE ONLY public."ClientIdPRestrictions" DROP CONSTRAINT "PK_ClientIdPRestrictions";
ALTER TABLE ONLY public."ClientGrantTypes" DROP CONSTRAINT "PK_ClientGrantTypes";
ALTER TABLE ONLY public."ClientCorsOrigins" DROP CONSTRAINT "PK_ClientCorsOrigins";
ALTER TABLE ONLY public."ClientClaims" DROP CONSTRAINT "PK_ClientClaims";
ALTER TABLE ONLY public."AspNetUsers" DROP CONSTRAINT "PK_AspNetUsers";
ALTER TABLE ONLY public."AspNetUserTokens" DROP CONSTRAINT "PK_AspNetUserTokens";
ALTER TABLE ONLY public."AspNetUserRoles" DROP CONSTRAINT "PK_AspNetUserRoles";
ALTER TABLE ONLY public."AspNetUserLogins" DROP CONSTRAINT "PK_AspNetUserLogins";
ALTER TABLE ONLY public."AspNetUserClaims" DROP CONSTRAINT "PK_AspNetUserClaims";
ALTER TABLE ONLY public."AspNetRoles" DROP CONSTRAINT "PK_AspNetRoles";
ALTER TABLE ONLY public."AspNetRoleClaims" DROP CONSTRAINT "PK_AspNetRoleClaims";
ALTER TABLE ONLY public."ApiSecrets" DROP CONSTRAINT "PK_ApiSecrets";
ALTER TABLE ONLY public."ApiScopes" DROP CONSTRAINT "PK_ApiScopes";
ALTER TABLE ONLY public."ApiScopeClaims" DROP CONSTRAINT "PK_ApiScopeClaims";
ALTER TABLE ONLY public."ApiResources" DROP CONSTRAINT "PK_ApiResources";
ALTER TABLE ONLY public."ApiProperties" DROP CONSTRAINT "PK_ApiProperties";
ALTER TABLE ONLY public."ApiClaims" DROP CONSTRAINT "PK_ApiClaims";
DROP TABLE public."PersistedGrants";
DROP TABLE public."IdentityResources";
DROP TABLE public."IdentityProperties";
DROP TABLE public."IdentityClaims";
DROP TABLE public."DeviceCodes";
DROP TABLE public."Clients";
DROP TABLE public."ClientSecrets";
DROP TABLE public."ClientScopes";
DROP TABLE public."ClientRedirectUris";
DROP TABLE public."ClientProperties";
DROP TABLE public."ClientPostLogoutRedirectUris";
DROP TABLE public."ClientIdPRestrictions";
DROP TABLE public."ClientGrantTypes";
DROP TABLE public."ClientCorsOrigins";
DROP TABLE public."ClientClaims";
DROP TABLE public."AspNetUsers";
DROP TABLE public."AspNetUserTokens";
DROP TABLE public."AspNetUserRoles";
DROP TABLE public."AspNetUserLogins";
DROP TABLE public."AspNetUserClaims";
DROP TABLE public."AspNetRoles";
DROP TABLE public."AspNetRoleClaims";
DROP TABLE public."ApiSecrets";
DROP TABLE public."ApiScopes";
DROP TABLE public."ApiScopeClaims";
DROP TABLE public."ApiResources";
DROP TABLE public."ApiProperties";
DROP TABLE public."ApiClaims";